### ISSUE TITLE
Create a release version

### ISSUE THREAD

**Issue by lpaulmp** [mrlesmithjr/ansible-cacti#1]
Is possible to create a release/tag in github, so in the future when some change lands in master, it won't broke to others that use this ansible galaxy. Thanks

**Comment by mrlesmithjr** [comment]
@lpaulmp You looking for Cacti release tags or actual incremental releases based on actual changes such as v0.1.0 to specify my release version?

**Comment by mrlesmithjr** [comment]
Done!
```
v0.1.0          Cacti Version 0.8.8g
```
